import './js/partials/header-link';
import './js/partials/hero.js';
import './js/partials/gallery/filters.js';
import './js/partials/gallery/all-recipes.js';
import './js/partials/gallery/popular.js';
import './js/partials/gallery/load-filter-options.js';
import './js/partials/gallery/all-categories.js';
import './js/partials/modals/modal-recipes.js';
import './js/open-modal/open-modal.js';
import './js/open-modal/open-close-modals.js';
import './js/partials/pop-up-rating.js';
import './js/partials/footer.js';
import './js/partials/scroll-up.js';
import './js/partials/modals/order-now.js';
import './js/partials/pagination-home.js'
import './js/dark-theme.js';
